// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB44LABcVtw1iHMUAEoCpMawgT610ReEos',
    appId: '1:396347236702:web:8196f5609de3f3a11d6fcf',
    messagingSenderId: '396347236702',
    projectId: 'sports-sync-nitk',
    authDomain: 'sports-sync-nitk.firebaseapp.com',
    storageBucket: 'sports-sync-nitk.firebasestorage.app',
    measurementId: 'G-FPL9DYYZZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzdVSDJkgdMPj3aGufILnCGCKZE0FqR9I',
    appId: '1:396347236702:android:cfeb53cde99a8f981d6fcf',
    messagingSenderId: '396347236702',
    projectId: 'sports-sync-nitk',
    storageBucket: 'sports-sync-nitk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlB-okxktf1-RoqWyq033t6X6Q1tM2zBI',
    appId: '1:396347236702:ios:c6e67be1936997631d6fcf',
    messagingSenderId: '396347236702',
    projectId: 'sports-sync-nitk',
    storageBucket: 'sports-sync-nitk.firebasestorage.app',
    iosBundleId: 'com.example.sportsSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlB-okxktf1-RoqWyq033t6X6Q1tM2zBI',
    appId: '1:396347236702:ios:c6e67be1936997631d6fcf',
    messagingSenderId: '396347236702',
    projectId: 'sports-sync-nitk',
    storageBucket: 'sports-sync-nitk.firebasestorage.app',
    iosBundleId: 'com.example.sportsSync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB44LABcVtw1iHMUAEoCpMawgT610ReEos',
    appId: '1:396347236702:web:270d5f73693f3c2b1d6fcf',
    messagingSenderId: '396347236702',
    projectId: 'sports-sync-nitk',
    authDomain: 'sports-sync-nitk.firebaseapp.com',
    storageBucket: 'sports-sync-nitk.firebasestorage.app',
    measurementId: 'G-LPM414V6GV',
  );

}